### ISSUE TITLE
Guzzle and vendor dir missing

### ISSUE THREAD

**Issue by tristanbailey** [perfectwebteam/sparkpost#1]
Hi,

Issue with this one, so it can not find Guzzle, that is included, and autoload_real when first installed.
This file and dir are missing:

require_once __DIR__ . '/composer/autoload_real.php';

I am not sure if you meant them to be installed globally?

**Comment by roland-d** [comment]
Hello @tristanbailey I have pushed an update so that now all libraries are included. Can you check if it works for you now?

**Comment by tristanbailey** [comment]
Thanks for the update Roland, I got the smtp version running after the live domain change was working, but will try this in downtime later in the week.
